# Generated by Django 5.0.6 on 2024-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_socio_rename_socios_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=30)),
                ('años_experiencia', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Nuevos',
            },
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('fecha_ejecucion', 'nombre', 'ubicacion', 'tipo')},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='empresa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('nombre', 'ubicacion')},
        ),
    ]
