# Generated by Django 5.0.6 on 2024-06-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_nuevo_alter_profesional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuevo',
            options={},
        ),
        migrations.RenameField(
            model_name='nuevo',
            old_name='años_experiencia',
            new_name='años_de_experiencia',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='años_experiencia',
            new_name='años_de_experiencia',
        ),
    ]
