# Generated by Django 5.0.6 on 2024-06-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_nuevo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevo',
            old_name='años_de_experiencia',
            new_name='anos_de_experiencia',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='años_de_experiencia',
            new_name='anos_de_experiencia',
        ),
    ]
